export const ADMIN_ROUTE = '/admin'
export const PROFILE_ROUTE = '/profile'
export const CREATE_ROUTE = '/modals'
export const LOGIN_ROUTE = '/login'
export const ACTIVATE_ROUTE = '/activate'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const DEVICE_ROUTE = '/device'